### PR TITLE
Show play icons on mouse hover for "Show Download Status"

### PR DESCRIPTION
**Pull request by rasitayaz**
Uninstalled icons were being displayed on mouse hover, but play icons weren't, sorry to bother @Tormak9970

### CODE REVIEW

**Comment by Tormak9970** [comment]
will test when I have a chance

**Comment by Tormak9970** [comment]
@rasitayaz I tested it, and looks good except the circular varient's uninstalled icon only shows when you hover it, instead of when you hover the game portrait

**Comment by rasitayaz** [comment]
oh, let me check that and get back to you

**Comment by rasitayaz** [comment]
you're right, some other steam css was overwriting the opacity, fixed it now.

**Comment by Tormak9970** [comment]
will test when I get a chance

**Comment by Tormak9970** [comment]
looks good, merging

**Pull request merged**
