### PR TITLE
ShowDownloadStatus/shared.css: Modify values for more consistency wit…

### PR DESCRIPTION
**Pull request by someone5678**
…h SteamOS

This commit modifies Download Status Icon
to get more consistence with other SteamOS
components, especially Steam Deck Verified Icon.

* Resize download status box icon size and match bg-color with Steam Deck Verified icon
* Try to match padding as close as possible with Steam Deck Verified icon

### CODE REVIEW

**Comment by Tormak9970** [comment]
> …h SteamOS
> 
> This commit modifies Download Status Icon to get more consistence with other SteamOS components, especially Steam Deck Verified Icon.
> 
>     * Resize download status box icon size and match bg-color with Steam Deck Verified icon
> 
>     * Try to match padding as close as possible with Steam Deck Verified icon

The size difference is intentional. The **Uninstall** icon already exists with the styling, I simply matched it for the installed icon. If you provide screenshots of how your changes look (both installed and uninstalled) I will consider adding a toggle to switch between the different styles.

**Comment by someone5678** [comment]
> If you provide screenshots of how your changes look (both installed and uninstalled) I will consider adding a toggle to switch between the different styles.

https://imgur.com/a/3puMPOX

Here's what it looks like!

**Comment by Tormak9970** [comment]
> > If you provide screenshots of how your changes look (both installed and uninstalled) I will consider adding a toggle to switch between the different styles.
> 
> https://imgur.com/a/3puMPOX
> 
> Here's what it looks like!

Looks great! I'll add getting this integrated to my todo list. Not sure when it will happen but should be in a few weeks

**Comment by Tormak9970** [comment]
@someone5678 I have modified ShowDownloadStatus to accommodate a new mode with your changes called "Small Icons". Please modify your PR to resolve the conflicts

**Comment by someone5678** [comment]
> @someone5678 I have modified ShowDownloadStatus to accommodate a new mode with your changes called "Small Icons". Please modify your PR to resolve the conflicts

Closed pr because all the related parts are in small.css :)
Thanks!

**Comment by Tormak9970** [comment]
Added credit to the readme since the pr wont be merged

**Pull request closed without merging**
